<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "categorymanager"
 *
 * Auto generated by Extension Builder 2018-08-21
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Category Manager',
    'description' => 'Backend Module to manage System Categories',
    'category' => 'module',
    'author' => 'Oliver Beck',
    'author_email' => 'oliver.beck@intersim.ch',
    'state' => 'alpha',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '0.1',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.0-8.7.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
